# Generated by Django 5.2.1 on 2025-05-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quetsion',
            new_name='question',
        ),
    ]
